a=1
c=3
digitr=5 ; digit iteration
itr=6
x=10
y=12
tmp=14
newlin: asciz/
/
start:  reset
        dmove   y,[.00225]
        dmove   x,[0.99999746]
        movei   itr,0
next:   dmove   tmp,y           ; tmp = y
        dfmp    tmp,tmp         ; tmp = y*y
        dfmp    y,x             ; y = y*x
        dfmp    y,[2.0]         ; y = 2*y*x        
        dfmp    x,x             ; x = x*x
        dfsb    x,tmp           ; x = x*x - y*y
        dmove   a,x
        jsr     prflt           ; print x
        movei   tmp," "
        outchr  tmp             ; print space
        dmove   a,y
        jsr     prflt           ; print y
        outstr  newlin        
        addi    itr,1
        caig    itr,11          ; jump to exit when itr > 11
        jrst    next
        exit
prflt:  0                       ; print float less than one in accum a
        jumpge  a,point         ; jump if not negative
        movei   tmp,"-"         ; print negative sign
        outchr  tmp
        dfmp    a,[-1.0]        ; make it positive
point:  movei   tmp,"."         ; print period
        outchr  tmp
        movei   digitr,1        ; digitr is 1, digit iteration
dig:    dfmp    a,[10.0]        ; bring next digitr into ones place
        fix     tmp,a           ; integer
        fltr    c,tmp           ; float it
        dfsb    a,c             ; subtract off fraction
        addi    tmp,"0"         ; insure it's at least zero
        outchr  tmp             ; print it
        addi    digitr,1        ; add one to digitr
        caig    digitr,5        ; jump to return when digitr > 5
        jrst    dig
        jrstf   @prflt
end     start
        