#!/bin/bash
UTEXAS=utexas23-reconstruction

#rm -rf ./tmp
mkdir ./tmp

cp $UTEXAS/*.FOR ./tmp
cp $UTEXAS/*.MAC ./tmp
cp $UTEXAS/HLP/DECWAR.HLP ./tmp
cp $UTEXAS/HLP/DECWAR.NWS ./tmp
cp $UTEXAS/HLP/DECWAR.GRP ./tmp
cp msc/decwar.ini ./tmp

#cp msc/to-tape/* ./tmp

./back10 -cf ./tapes/$UTEXAS.tap ./tmp/*
./back10 -lf ./tapes/$UTEXAS.tap

